// Copyright (C) 2008  Maksim Sipos <msipos@mailc.net>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "ripe/ripe.h"

StringBuf* sb_contents;
StringBuf* sb_header;
StringBuf* sb_init1a;
StringBuf* sb_init1b;
StringBuf* sb_init2;
StringBuf* sb_init3;

void dump_init()
{
  sb_contents = mem_new(StringBuf);
  sb_header = mem_new(StringBuf);
  sb_init1a = mem_new(StringBuf);
  sb_init1b = mem_new(StringBuf);
  sb_init2 = mem_new(StringBuf);
  sb_init3 = mem_new(StringBuf);
  sbuf_init(sb_contents, "");
  sbuf_init(sb_header, "");
  sbuf_init(sb_init1a, "");
  sbuf_init(sb_init1b, "");
  sbuf_init(sb_init2, "");
  sbuf_init(sb_init3, "");
}

void dump_output(FILE* f, const char* module_name)
{
  fprintf(f, "// %s.c -- Autogenerated by Ripec\n", module_name);
  fprintf(f, "#include \"modules/modules.h\"\n");
  fprintf(f, "%s", sb_header->str);
  fprintf(f, "%s", sb_contents->str);

  fprintf(f, "void init1a_%s(){\n", module_name);
  fprintf(f, "%s", sb_init1a->str);
  fprintf(f, "}\n");

  fprintf(f, "void init1b_%s(){\n", module_name);
  fprintf(f, "%s", sb_init1b->str);
  fprintf(f, "}\n");

  fprintf(f, "void init2_%s(){\n", module_name);
  fprintf(f, "%s", sb_init2->str);
  fprintf(f, "}\n");

  fprintf(f, "void init3_%s(){\n", module_name);
  fprintf(f, "%s", sb_init3->str);
  fprintf(f, "}\n");
}
