// Copyright (C) 2008  Maksim Sipos <msipos@mailc.net>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "lang/lang.h"

static StringBuf* sb_contents;
static StringBuf* sb_header;
static StringBuf* sb_init1a;
static StringBuf* sb_init1b;
static StringBuf* sb_init2;
static StringBuf* sb_init3;

void wr_init()
{
  sb_contents = mem_new(StringBuf);
  sb_header = mem_new(StringBuf);
  sb_init1a = mem_new(StringBuf);
  sb_init1b = mem_new(StringBuf);
  sb_init2 = mem_new(StringBuf);
  sb_init3 = mem_new(StringBuf);
  sbuf_init(sb_contents, "");
  sbuf_init(sb_header, "");
  sbuf_init(sb_init1a, "");
  sbuf_init(sb_init1b, "");
  sbuf_init(sb_init2, "");
  sbuf_init(sb_init3, "");
}

void wr_print(int destination, const char* format, ...)
{
  slog("wr_print -> %d", destination);

  va_list ap;
  va_start(ap, format);
  // Calculate needed buffer
  int sz = vsnprintf(NULL, 0, format, ap) + 1;
  va_end(ap);

  char tmpbuf[sz];
  va_start(ap, format);
  vsnprintf(tmpbuf, sz, format, ap);
  tmpbuf[sz - 1] = 0;
  va_end(ap);

  slog("##>>%s<<##", tmpbuf);

  StringBuf* dest = NULL;
  switch(destination){
    case WR_INIT1A:
      dest = sb_init1a;
      break;
    case WR_INIT1B:
      dest = sb_init1b;
      break;
    case WR_INIT2:
      dest = sb_init2;
      break;
    case WR_INIT3:
      dest = sb_init3;
      break;
    case WR_CODE:
      dest = sb_contents;
      break;
    case WR_HEADER:
      dest = sb_header;
      break;
    default:
      assert_never();
  }

  sbuf_cat(dest, tmpbuf);
}

const char* wr_dump(const char* module_name)
{
  StringBuf sb;
  sbuf_init(&sb, "");
  sbuf_printf(&sb, "// %s.c -- Autogenerated by Ripec\n", module_name);
  sbuf_printf(&sb, "#include \"modules/modules.h\"\n");
  sbuf_printf(&sb, "%s", sb_header->str);
  sbuf_printf(&sb, "%s", sb_contents->str);

  sbuf_printf(&sb, "void init1a_%s(){\n", module_name);
  sbuf_printf(&sb, "%s", sb_init1a->str);
  sbuf_printf(&sb, "}\n");

  sbuf_printf(&sb, "void init1b_%s(){\n", module_name);
  sbuf_printf(&sb, "%s", sb_init1b->str);
  sbuf_printf(&sb, "}\n");

  sbuf_printf(&sb, "void init2_%s(){\n", module_name);
  sbuf_printf(&sb, "%s", sb_init2->str);
  sbuf_printf(&sb, "}\n");

  sbuf_printf(&sb, "void init3_%s(){\n", module_name);
  sbuf_printf(&sb, "%s", sb_init3->str);
  sbuf_printf(&sb, "}\n");
  return (const char*) sb.str;
}
